import { DanceEvent } from "@/types";

export const events: DanceEvent[] = [
  // February 2026
  {
    id: "jcf-202602-001",
    name: "ダンシングギャラクシー京都",
    organizer: "JCF",
    location: "島津アリーナ京都",
    date: "2026-02-08",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jcf-seibu.com/schedule.html",
    year: 2026,
    month: 2,
  },
  {
    id: "jdc-202602-001",
    name: "東京アマチュア競技会",
    organizer: "JDC",
    location: "コンフォートホール大宮",
    date: "2026-02-07",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 2,
  },
  {
    id: "jdc-202602-002",
    name: "東京ダンス選手権",
    organizer: "JDC",
    location: "産業貿易センター台東館",
    date: "2026-02-08",
    category: "スタンダード/ラテン",
    level: "プロ",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 2,
  },
  {
    id: "jdc-202602-003",
    name: "2026gentil Cupアジアオープンダンス選手権大会",
    organizer: "JDC",
    location: "グランドプリンスホテル新高輪「飛天」",
    date: "2026-02-22",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 2,
  },
  {
    id: "jdc-202602-004",
    name: "ダンシンググランプリ西部",
    organizer: "JDC",
    location: "高石市立総合体育館",
    date: "2026-02-15",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 2,
  },
  {
    id: "jbdf-202602-001",
    name: "2026スーパージャパンカップダンス",
    organizer: "JBDF",
    location: "幕張イベントホール",
    date: "2026-02-28",
    dateEnd: "2026-03-01",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf.or.jp/contest/super.html",
    year: 2026,
    month: 2,
  },
  // March 2026
  {
    id: "jdsf-260301",
    name: "全国ダンススポーツ競技会香川大会",
    organizer: "JDSF",
    location: "香川",
    date: "2026-03-08",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260302",
    name: "ダンススポーツ競技会九州ブロック選手権in佐賀",
    organizer: "JDSF",
    location: "佐賀",
    date: "2026-03-08",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260303",
    name: "岩手県ダンススポーツ大会in滝沢",
    organizer: "JDSF",
    location: "岩手県",
    date: "2026-03-29",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260304",
    name: "茨城県県北地区ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "茨城県",
    date: "2026-03-07",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260305",
    name: "鎌倉市ダンススポーツ大会",
    organizer: "JDSF",
    location: "鎌倉市",
    date: "2026-03-15",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260306",
    name: "福島市ダンススポーツ大会",
    organizer: "JDSF",
    location: "福島市",
    date: "2026-03-15",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260307",
    name: "府中市ダンススポーツ大会",
    organizer: "JDSF",
    location: "府中市",
    date: "2026-03-29",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260308",
    name: "九州ダンススポーツ競技会鹿児島大会",
    organizer: "JDSF",
    location: "鹿児島",
    date: "2026-03-15",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260309",
    name: "多摩北ブロックダンススポーツ大会",
    organizer: "JDSF",
    location: "未定",
    date: "2026-03-08",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260310",
    name: "千葉県ダンススポーツ選手権",
    organizer: "JDSF",
    location: "千葉県",
    date: "2026-03-29",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260311",
    name: "山梨県ダンススポーツ大会",
    organizer: "JDSF",
    location: "山梨県",
    date: "2026-03-15",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260312",
    name: "宇都宮市ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "宇都宮市",
    date: "2026-03-28",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260313",
    name: "ユース10ダンス選手権・京都府ダンススポーツ競技会",
    organizer: "JDSF",
    location: "京都府",
    date: "2026-03-08",
    category: "スタンダード/ラテン",
    level: "ジュニア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260314",
    name: "全国ダンススポーツ競技会愛媛大会",
    organizer: "JDSF",
    location: "愛媛県",
    date: "2026-03-01",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260315",
    name: "愛知県ダンススポーツ選手権大会",
    organizer: "JDSF",
    location: "愛知県",
    date: "2026-03-15",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260316",
    name: "印旛郡市ダンススポーツ競技大会in富里",
    organizer: "JDSF",
    location: "富里",
    date: "2026-03-20",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260317",
    name: "全日本PD10ダンス選手権・九州大会in宗像",
    organizer: "JDSF",
    location: "宗像",
    date: "2026-03-20",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260318",
    name: "ダンススポーツ・全日本シニア10ダンス選手権",
    organizer: "JDSF",
    location: "未定",
    date: "2026-03-29",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260320",
    name: "PD東海北陸ブロック競技会in岐阜",
    organizer: "JDSF",
    location: "岐阜",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260322",
    name: "PD西部ブロックダンススポーツ競技会",
    organizer: "JDSF",
    location: "未定",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260323",
    name: "江東区ダンススポーツ大会",
    organizer: "JDSF",
    location: "江東区",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jdsf-260325",
    name: "ダンススポーツフェスティバルin日野",
    organizer: "JDSF",
    location: "日野",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 3,
  },
  {
    id: "jcf-202603-001",
    name: "ダンシングギャラクシー滋賀",
    organizer: "JCF",
    location: "プロシードアリーナHIKONE",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jcf-seibu.com/schedule.html",
    year: 2026,
    month: 3,
  },
  {
    id: "jdc-202603-001",
    name: "JDCプロフェッショナル10ダンス選手権",
    organizer: "JDC",
    location: "邦和みなとスポーツ&カルチャー",
    date: "2026-03-15",
    category: "10ダンス",
    level: "プロ",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 3,
  },
  {
    id: "jdc-202603-002",
    name: "ジャパンカップダンス選手権in広島",
    organizer: "JDC",
    location: "福山通運ローズアリーナ",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 3,
  },
  {
    id: "jbdf-202603-001",
    name: "全日本10ダンス選手権大会",
    organizer: "JBDF",
    location: "都ホテル尼崎",
    date: "2026-03-29",
    category: "10ダンス",
    level: "プロ/アマ",
    url: "https://jbdf.or.jp/contest/10dance.html",
    year: 2026,
    month: 3,
  },
  // April 2026
  {
    id: "jdsf-260401",
    name: "全国ダンススポーツ競技会北海道大会in札幌",
    organizer: "JDSF",
    location: "札幌",
    date: "2026-04-05",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260402",
    name: "群馬県ダンススポーツ大会",
    organizer: "JDSF",
    location: "群馬県",
    date: "2026-04-11",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260403",
    name: "全国ダンススポーツ競技島根大会",
    organizer: "JDSF",
    location: "島根県",
    date: "2026-04-12",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260404",
    name: "全国ダンススポーツ競技会鳥取大会",
    organizer: "JDSF",
    location: "鳅取県",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260405",
    name: "関東甲信越ブロックシニアⅡ:en:organizer: "JDSF",
    location: "神奈川県",
    date: "2026-04-12",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260406",
    name: "前期ダンススポーツ東北ブロック選手権in福島",
    organizer: "JDSF",
    location: "福島",
    date: "2026-04-12",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260407",
    name: "ダンススポーツ競技山口大会",
    organizer: "JDSF",
    location: "山口県",
    date: "2026-04-19",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260408",
    name: "九州ダンススポーツ競技会福岡大会",
    organizer: "JDSF",
    location: "福岡",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260411",
    name: "茨城県南地区春期ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "茨城県",
    date: "2026-04-19",
    category: "スタン�26-04-19",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260412",
    name: "千葉ダンススポーツ選手権シニアⅢ",
    organizer: "JDSF",
    location: "千葉県",
    date: "2026-04-19",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260413",
    name: "北海道ダンススポーツ選手権大会",
    organizer: "JDSF",
    location: "北海道",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260414",
    name: "栃木県ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "栃木県",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260415",
    name: "浜松市ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "浜松市",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260416",
    name: "ダンススポーツグランプリin京都",
    organizer: "JDSF",
    location: "京都",
    date: "2026-04-19",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260417",
    name: "狭山市ダンススポーツ大会",
    organizer: "JDSF",
    location: "狭山市",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260419",
    name: "埼玉県ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "埼玉県",
    date: "2026-04-12",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260421",
    name: "PD関東甲信越ブロック競技会",
    organizer: "JDSF",
    location: "未定",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260423",
    name: "兵庫県ダンススポーツ選手権大会",
    organizer: "JDSF",
    location: "兵庫県",
    date: "2026-04-29",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260424",
    name: "ひたちなか市ダンススポーツ大会",
    organizer: "JDSF",
    location: "ひたちなか市",
    date: "2026-04-29",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260425",
    name: "山形県ダンススポーツ競技会",
    organizer: "JDSF",
    location: "山形県",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260426",
    name: "東京都スポーツ大会春季ダンススポーツ",
    organizer: "JDSF",
    location: "東京都",
    date: "2026-04-25",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260427",
    name: "多摩中央ブロックダンススポーツ大会",
    organizer: "JDSF",
    location: "未定",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdsf-260428",
    name: "東京都ダンススポーツ競技会in日野",
    organizer: "JDSF",
    location: "日野",
    date: "2026-04-11",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 4,
  },
  {
    id: "jdc-202604-001",
    name: "JDC西部ダンス選手権「前期」",
    organizer: "JDC",
    location: "京都市伏見港公園体育館",
    date: "2026-04-05",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 4,
  },
  {
    id: "jdc-202604-002",
    name: "イーストジャパンダンス選手権",
    organizer: "JDC",
    location: "産業貿易センター浜松町館4F",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 4,
  },
  {
    id: "jcf-202604-001",
    name: "WDT杯 東部日本ダンス選手権大会",
    organizer: "JCF",
    location: "都立産業貿易センター台東館7F",
    date: "2026-04-12",
    entryDeadline: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jcf-tokyo.com/schedule/index.html",
    year: 2026,
    month: 4,
  },
  // May 2026
  {
    id: "jdsf-260501",
    name: "石川県ダンススポーツ選手権大会",
    organizer: "JDSF",
    location: "石川県",
    date: "2026-05-10",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260502",
    name: "岐阜県ダンススポーツ大会",
    organizer: "JDSF",
    location: "岐阜県",
    date: "2026-05-04",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260503",
    name: "奈良県ダンススポーツ競技会",
    organizer: "JDSF",
    location: "奈良県",
    date: "2026-05-03",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260504",
    name: "高崎市ダンススポーツ大会",
    organizer: "JDSF",
    location: "高崎市",
    date: "2026-05-02",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260505",
    name: "松戸市民ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "松戸市",
    date: "2026-05-02",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260506",
    name: "DSC神奈川杯",
    organizer: "JDSF",
    location: "神奈川県",
    date: "2026-05-09",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260507",
    name: "仙台市ダンススポーツ大会",
    organizer: "JDSF",
    location: "仙台市",
    date: "2026-05-06",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260508",
    name: "新潟県ダンススポーツ大会",
    organizer: "JDSF",
    location: "新潟県",
    date: "2026-05-17",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260509",
    name: "千葉県ダンススポーツ選手権大会",
    organizer: "JDSF",
    location: "千葉県",
    date: "2026-05-09",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260510",
    name: "PD兵庫県支部ダンススポーツ競技会",
    organizer: "JDSF",
    location: "兵庫県",
    date: "2026-05-10",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260511",
    name: "東京多摩南ブロックダンススポーツ大会",
    organizer: "JDSF",
    location: "未定",
    date: "2026-05-03",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260512",
    name: "豊島区ダンススポーツ大会",
    organizer: "JDSF",
    location: "豊島区",
    date: "2026-05-05",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260513",
    name: "埼玉県ジュニアダンススポーツ大会",
    organizer: "JDSF",
    location: "埼玉県",
    date: "2026-05-05",
    category: "スタンダード/ラテン",
    level: "ジュニア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260514",
    name: "大阪府ダンススポーツ選手権",
    organizer: "JDSF",
    location: "大阪府",
    date: "2026-05-31",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260515",
    name: "東京オープンダンススポーツ選手権【1日目】",
    organizer: "JDSF",
    location: "東京都",
    date: "2026-05-23",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260516",
    name: "東京オープンダンススポーツ選手権【2日目】",
    organizer: "JDSF",
    location: "東京都",
    date: "2026-05-24",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260517",
    name: "PD東海北陸ブロック競技会in愛知",
    organizer: "JDSF",
    location: "愛知",
    date: "2026-05-31",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260518",
    name: "PD九州ダンススポーツ競技大会in諫早",
    organizer: "JDSF",
    location: "諫早",
    date: "2026-05-17",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260519",
    name: "栃木県北ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "栃木県",
    date: "2026-05-10",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260520",
    name: "世田谷区ダンススポーツ大会",
    organizer: "JDSF",
    location: "世田谷区",
    date: "2026-05-10",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260521",
    name: "全国ダンススポーツ競技会徳島大会",
    organizer: "JDSF",
    location: "徳島県",
    date: "2026-05-17",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260522",
    name: "相模原市ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "相模原市",
    date: "2026-05-30",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260523",
    name: "城東ブロックダンススポーツ競技会",
    organizer: "JDSF",
    location: "未定",
    date: "2026-05-03",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260524",
    name: "ダンススポーツフェスティバルin東京",
    organizer: "JDSF",
    location: "東京都",
    date: "2026-05-31",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260525",
    name: "関東甲信越ブロック選手権シニアV",
    organizer: "JDSF",
    location: "未定",
    date: "2026-05-31",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdsf-260526",
    name: "PD関東甲信越ブロック競技会",
    organizer: "JDSF",
    location: "未定",
    date: "2026-05-31",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 5,
  },
  {
    id: "jdc-202605-001",
    name: "東京アマチュア競技会 in 大宮",
    organizer: "JDC",
    location: "コンフォートホール大宮",
    date: "2026-05-02",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 5,
  },
  {
    id: "jdc-202605-002",
    name: "プロデモンストレーション競技会",
    organizer: "JDC",
    location: "都立産業貿易センター浜松町館3F",
    date: "2026-05-05",
    category: "スタンダード/ラテン",
    level: "プロ",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 5,
  },
  {
    id: "jdc-202605-003",
    name: "アマチュアグランプリ西部",
    organizer: "JDC",
    location: "KTM河本工業総合体育館",
    date: "2026-05-23",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 5,
  },
  // June 2026
  {
    id: "jdsf-260601",
    name: "全日本選手権10ダンス・東海北陸ブロック選手権",
    organizer: "JDSF",
    location: "未定",
    date: "2026-06-07",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260602",
    name: "青の界めきあおもりダンススポーツ大会",
    organizer: "JDSF",
    location: "青森県",
    date: "2026-06-14",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260603",
    name: "PD東海北陸ブロック競技会in三重",
    organizer: "JDSF",
    location: "三重",
    date: "2026-06-21",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260604",
    name: "福島県総合スポーツ大会ダンススポーツ競技",
    organizer: "JDSF",
    location: "福島県",
    date: "2026-06-07",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260605",
    name: "山形県ダンススポーツ競技会",
    organizer: "JDSF",
    location: "山形県",
    date: "2026-06-21",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260606",
    name: "PD九州ダンススポーツ競技大会in鹿児島",
    organizer: "JDSF",
    location: "鹿児島",
    date: "2026-06-07",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260607",
    name: "宮城県ダンススポーツ石巻大会",
    organizer: "JDSF",
    location: "石巻",
    date: "2026-06-28",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260608",
    name: "ランキングチャレンジin静岡",
    organizer: "JDSF",
    location: "静岡",
    date: "2026-06-21",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260609",
    name: "沉県ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "沖縄県",
    date: "2026-06-21",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260610",
    name: "長野県ダンススポーツ大会",
    organizer: "JDSF",
    location: "長野県",
    date: "2026-06-14",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260611",
    name: "茨城県ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "茨城県",
    date: "2026-06-06",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260612",
    name: "PDグランプリカップin福岡",
    organizer: "JDSF",
    location: "福岡",
    date: "2026-06-21",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260613",
    name: "PD大阪府支部ダンススポーツ競技会",
    organizer: "JDSF",
    location: "大阪府",
    date: "2026-06-28",
    category: "スタンダード/ラテン",
    level: "派遣選考会",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260614",
    name: "真岡市ダンススポーツ競技大会",
    organizer: "JDSF",
    location: "真岡市",
    date: "2026-06-14",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdsf-260615",
    name: "千葉市ダンススポーツ競技会",
    organizer: "JDSF",
    location: "千葉市",
    date: "2026-06-14",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 6,
  },
  {
    id: "jdc-202606-001",
    name: "ジャパンカップダンス選手権in東部",
    organizer: "JDC",
    location: "産業貿易センター台東館5F",
    date: "2026-06-07",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jdctobu8.webnode.jp/2026/",
    year: 2026,
    month: 6,
  },
  {
    id: "jdc-202606-002",
    name: "JDCプレミアカップ",
    organizer: "JDC",
    location: "グランドプリンスホテル新高輪「飛天」",
    date: "2026-06-14",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jdc-dance.org/contestnews/",
    year: 2026,
    month: 6,
  },
  {
    id: "jdc-202606-003",
    name: "ジャパンカップダンス選手権in九州",
    organizer: "JDC",
    location: "福岡自治研修センター",
    date: "2026-06-21",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 6,
  },
  {
    id: "jbdf-202606-001",
    name: "日本インターナショナルダンス選手権大会",
    organizer: "JBDF",
    location: "グランドプリンスホテル新高輪「飛天」",
    date: "2026-06-06",
    dateEnd: "2026-06-07",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf.or.jp/contest/inter.html",
    year: 2026,
    month: 6,
  },
  // July 2026
  {
    id: "jdsf-260701",
    name: "オールジャパン・ジュニアダンススポーツカップ【1日目】",
    organizer: "JDSF",
    location: "未定",
    date: "2026-07-25",
    category: "スタンダード/ラテン",
    level: "ジュニア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 7,
  },
  {
    id: "jdsf-260702",
    name: "オールジャパン・ジュニアダンススポーツカップ【2日目】",
    organizer: "JDSF",
    location: "未定",
    date: "2026-07-26",
    category: "スタンダード/ラテン",
    level: "ジュニア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 7,
  },
  {
    id: "jdsf-260703",
    name: "ダンススポーツグランプリin静岡",
    organizer: "JDSF",
    location: "静岡",
    date: "2026-07-12",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 7,
  },
  {
    id: "jdsf-260704",
    name: "横浜市ダンススポーツ大会",
    organizer: "JDSF",
    location: "横浜市",
    date: "2026-07-11",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://adm.jdsf.jp/competition/index.php",
    year: 2026,
    month: 7,
  },
  {
    id: "jdc-202607-001",
    name: "JPカップ西部",
    organizer: "JDC",
    location: "大阪市立西成区民センター",
    date: "2026-07-19",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 7,
  },
  // August 2026
  {
    id: "jcf-202608-001",
    name: "JCF西部日本ダンス選手権大会",
    organizer: "JCF",
    location: "京都伏見港公園体育館",
    date: "2026-08-30",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jcf-seibu.com/schedule.html",
    year: 2026,
    month: 8,
  },
  // September 2026
  {
    id: "jdc-202609-001",
    name: "アマチュアグランプリ広島",
    organizer: "JDC",
    location: "尾道市長者ヶゟスポーツセンター",
    date: "2026-09-22",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 9,
  },
  // October 2026
  {
    id: "jcf-202610-001",
    name: "ダンシングギャラクシー京都Ⅱ",
    organizer: "JCF",
    location: "島津アリーナ京都",
    date: "2026-10-11",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jcf-seibu.com/schedule.html",
    year: 2026,
    month: 10,
  },
  {
    id: "jcf-202610-002",
    name: "JCFゴールデンチャンピオンシップス",
    organizer: "JCF",
    location: "金沢東急ホテル",
    date: "2026-10-12",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jcf-seibu.com/schedule.html",
    year: 2026,
    month: 10,
  },
  {
    id: "jdc-202610-001",
    name: "オールウェスト岡山",
    organizer: "JDC",
    location: "玉島市民交流センター",
    date: "2026-10-25",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 10,
  },
  // November 2026
  {
    id: "jdc-202611-001",
    name: "ニュースターボールダンス選手権",
    organizer: "JDC",
    location: "京都市伏見港公園体育館",
    date: "2026-11-14",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "http://www.jdc-seibu.com/",
    year: 2026,
    month: 11,
  },
  // EJBDF (東部日本ボールルームダンス���盟) Events
  {
    id: "ejbdf-202602-001",
    name: "アレックス・ムーアカップ/マダム・ロー杯2026",
    organizer: "JBDF",
    location: "グランドプリンスホテル新高輪「飛天」",
    date: "2026-02-08",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/eventpods/20260208/",
    year: 2026,
    month: 2,
  },
  {
    id: "ejbdf-202603-001",
    name: "前期・桝岡杯 東部日本ダンス選手権",
    organizer: "JBDF",
    location: "大さん橋ホール",
    date: "2026-03-08",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 3,
  },
  {
    id: "ejbdf-202603-002",
    name: "東北オープン選手権",
    organizer: "JBDF",
    location: "福島トヨタクラウンアリーナ",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/eventpods/20260322/",
    year: 2026,
    month: 3,
  },
  {
    id: "ejbdf-202603-003",
    name: "二ツュ司チャレンジカップ",
    organizer: "JBDF",
    location: "都立産業貿易センター浜松町館",
    date: "2026-03-22",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 3,
  },
  {
    id: "ejbdf-202604-001",
    name: "C級ダンス競技会 in 駒沢",
    organizer: "JBDF",
    location: "駒沢オリンピック公園屋内球技場",
    date: "2026-04-04",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 4,
  },
  {
    id: "ejbdf-202604-002",
    name: "C級ダンス競技会 in 横浜",
    organizer: "JBDF",
    location: "横浜市技能文化会館",
    date: "2026-04-12",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 4,
  },
  {
    id: "ejbdf-202604-003",
    name: "B級ダンス競技会",
    organizer: "JBDF",
    location: "都立産業貿易センター浜松町館",
    date: "2026-04-19",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/eventpods/20260419/",
    year: 2026,
    month: 4,
  },
  {
    id: "ejbdf-202604-004",
    name: "関東甲信越ダンス選手権（前期）",
    organizer: "JBDF",
    location: "ヤマト市民体育館（群馬県）",
    date: "2026-04-26",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 4,
  },
  {
    id: "ejbdf-202605-001",
    name: "C級ダンス競技会 in 台東",
    organizer: "JBDF",
    location: "台東区民会館",
    date: "2026-05-06",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 5,
  },
  {
    id: "ejbdf-202605-002",
    name: "神奈川ダンス選手権",
    organizer: "JBDF",
    location: "大さん橋ホール",
    date: "2026-05-10",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/eventpods/20260510/",
    year: 2026,
    month: 5,
  },
  {
    id: "ejbdf-202605-003",
    name: "B級ダンス競技会 in 浜松町",
    organizer: "JBDF",
    location: "都立産業貿易センター浜松町館",
    date: "2026-05-31",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 5,
  },
  {
    id: "ejbdf-202606-001",
    name: "東日本県別アマチュア対抗競技会",
    organizer: "JBDF",
    location: "福島トヨタクラウンアリーナ",
    date: "2026-06-24",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 6,
  },
  {
    id: "ejbdf-202607-001",
    name: "東京ダンス選手権",
    organizer: "JBDF",
    location: "都立産業貿易センター浜松町館",
    date: "2026-07-05",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/eventpods/20260705/",
    year: 2026,
    month: 7,
  },
  {
    id: "ejbdf-202609-001",
    name: "B級ダンス競技会 in 浜松町（秋）",
    organizer: "JBDF",
    location: "都立産業貿易センター浜松町館",
    date: "2026-09-06",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 9,
  },
  {
    id: "ejbdf-202609-002",
    name: "関東甲信越ダンス選手権（後期）",
    organizer: "JBDF",
    location: "ヤマト市民体育館（群馬県）",
    date: "2026-09-23",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 9,
  },
  {
    id: "ejbdf-202609-003",
    name: "後期 東部日本ダンス選手権",
    organizer: "JBDF",
    location: "大さん橋ホール",
    date: "2026-09-27",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 9,
  },
  {
    id: "ejbdf-202610-001",
    name: "C級ダンス競技会 in 横浜（秋）",
    organizer: "JBDF",
    location: "横浜市技能文化会館",
    date: "2026-10-04",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 10,
  },
  {
    id: "ejbdf-202610-002",
    name: "B級ダンス競技会 in 浜松町（秋）",
    organizer: "JBDF",
    location: "都立産業貿易センター浜松町館",
    date: "2026-10-11",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 10,
  },
  {
    id: "ejbdf-202610-003",
    name: "JBDF全日本選手権大会",
    organizer: "JBDF",
    location: "静岡県コンベンションアーツセンターグランシップ",
    date: "2026-10-24",
    dateEnd: "2026-10-25",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 10,
  },
  {
    id: "ejbdf-202611-001",
    name: "第27回統一全日本ダンス選手権大会",
    organizer: "JBDF",
    location: "グランドプリンスホテル新高輪「飛天」",
    date: "2026-11-03",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 11,
  },
  {
    id: "ejbdf-202611-002",
    name: "シニア・Gシニアダンス選手権",
    organizer: "JBDF",
    location: "台東区民会館",
    date: "2026-11-23",
    category: "スタンダード/ラテン",
    level: "アマチュア",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 11,
  },
  {
    id: "ejbdf-202611-003",
    name: "全沉縄選手権シーサー景",
    organizer: "JBDF",
    location: "ホテルモーリアクラシック",
    date: "2026-11-29",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 11,
  },
  {
    id: "ejbdf-202612-001",
    name: "全関東ダンス選手権大会",
    organizer: "JBDF",
    location: "大さん橋ホール",
    date: "2026-12-06",
    category: "スタンダード/ラテン",
    level: "プロ/アマ",
    url: "https://jbdf-ejd.gr.jp/event/",
    year: 2026,
    month: 12,
  },
];
