services:
  - type: web
    runtime: node
    name: odoroom
    repo: https://github.com/sneed-ay/odoroom
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
