import { NextRequest, NextResponse } from 'next/server';
import { getServiceSupabase } from '@/lib/supabase';

// GET /api/posts - Fetch all partner posts
export async function GET() {
  try {
      const supabase = getServiceSupabase();

          const { data, error } = await supabase
                .from('partner_posts')
                      .select(`
                              *,
                                      users (
                                                display_name,
                                                          picture_url,
                                                                    line_user_id
                                                                            )
                                                                                  `)
                                                                                        .order('created_at', { ascending: false });

                                                                                            if (error) {
                                                                                                  console.error('Error fetching posts:', error);
                                                                                                        return NextResponse.json({ error: 'Failed to fetch posts' }, { status: 500 });
                                                                                                            }

                                                                                                                return NextResponse.json({ posts: data });
                                                                                                                  } catch (error) {
                                                                                                                      console.error('Posts fetch error:', error);
                                                                                                                          return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
                                                                                                                            }
                                                                                                                            }

                                                                                                                            // POST /api/posts - Create a new partner post
                                                                                                                            export async function POST(request: NextRequest) {
                                                                                                                              try {
                                                                                                                                  const { lineUserId, title, content, danceType, area, role, level } = await request.json();

                                                                                                                                      if (!lineUserId || !title || !content || !danceType || !area || !role) {
                                                                                                                                            return NextResponse.json(
                                                                                                                                                    { error: 'Missing required fields' },
                                                                                                                                                            { status: 400 }
                                                                                                                                                                  );
                                                                                                                                                                      }

                                                                                                                                                                          const supabase = getServiceSupabase();

                                                                                                                                                                              // Get user ID from line_user_id
                                                                                                                                                                                  const { data: user, error: userError } = await supabase
                                                                                                                                                                                        .from('users')
                                                                                                                                                                                              .select('id')
                                                                                                                                                                                                    .eq('line_user_id', lineUserId)
                                                                                                                                                                                                          .single();

                                                                                                                                                                                                              if (userError || !user) {
                                                                                                                                                                                                                    return NextResponse.json({ error: 'User not found' }, { status: 404 });
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                            const { data, error } = await supabase
                                                                                                                                                                                                                                  .from('partner_posts')
                                                                                                                                                                                                                                        .insert({
                                                                                                                                                                                                                                                user_id: user.id,
                                                                                                                                                                                                                                                        title,
                                                                                                                                                                                                                                                                content,
                                                                                                                                                                                                                                                                        dance_type: danceType,
                                                                                                                                                                                                                                                                                area,
                                                                                                                                                                                                                                                                                        role,
                                                                                                                                                                                                                                                                                                level: level || 'beginner',
                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                            .select(`
                                                                                                                                                                                                                                                                                                                    *,
                                                                                                                                                                                                                                                                                                                            users (
                                                                                                                                                                                                                                                                                                                                      display_name,
                                                                                                                                                                                                                                                                                                                                                picture_url,
                                                                                                                                                                                                                                                                                                                                                          line_user_id
                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                        `)
                                                                                                                                                                                                                                                                                                                                                                              .single();

                                                                                                                                                                                                                                                                                                                                                                                  if (error) {
                                                                                                                                                                                                                                                                                                                                                                                        console.error('Error creating post:', error);
                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json({ error: 'Failed to create post' }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                      return NextResponse.json({ post: data }, { status: 201 });
                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Post creation error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                  // DELETE /api/posts - Delete a post (only by owner)
                                                                                                                                                                                                                                                                                                                                                                                                                  export async function DELETE(request: NextRequest) {
                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                        const { postId, lineUserId } = await request.json();

                                                                                                                                                                                                                                                                                                                                                                                                                            if (!postId || !lineUserId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                  return NextResponse.json(
                                                                                                                                                                                                                                                                                                                                                                                                                                          { error: 'postId and lineUserId are required' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  { status: 400 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                const supabase = getServiceSupabase();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Verify ownership
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { data: post, error: fetchError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .from('partner_posts')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .select('id, user_id, users!inner(line_user_id)')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .eq('id', postId)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .single();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (fetchError || !post) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return NextResponse.json({ error: 'Post not found' }, { status: 404 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const postOwnerLineId = (post.users as unknown as { line_user_id: string }).line_user_id;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (postOwnerLineId !== lineUserId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return NextResponse.json({ error: 'Unauthorized' }, { status: 403 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { error: deleteError } = await supabase
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .from('partner_posts')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .delete()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .eq('id', postId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (deleteError) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error('Error deleting post:', deleteError);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return NextResponse.json({ error: 'Failed to delete post' }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return NextResponse.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Post deletion error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }